### PR TITLE
Add AUR to README

### PR DESCRIPTION
**Pull request by apandada1**
I have made two AUR packages for Arch Linux and derivatives.

The package `share-preview` downloads the source and compiles with Rust (it takes quite a while to compile, and the compiled libraries take 2.5 GB space, like most other Rust apps :worried:. However they can be easily cleaned with the package manager. ).

That is why, I have also made the `share-preview-bin` package with the compiled binary (only a 2 MB download :smiley:, and 5.8 MB when installed  ). I have uploaded the compiled binary to [my fork](https://github.com/apandada1/share-preview/releases/tag/0.1.2).

### CODE REVIEW

**Comment by rafaelmardojai** [comment]
What mechanism are you using to generate the binary? 

I could also upload the compiled binary to the releases page if that ease things, I guess other packagers also would be interested in having that.

**Comment by apandada1** [comment]
The packaging system of Arch builds the following directory structure automatically from the PKGBUILD.

I compressed it into a [tar.gz](https://github.com/apandada1/share-preview/releases/tag/0.1.2). The `share-preview-bin` build script will simply download it and copy the files.

```
$ tree
.
└── usr
    ├── bin
    │   └── share-preview
    └── share
        ├── applications
        │   └── com.rafaelmardojai.SharePreview.desktop
        ├── glib-2.0
        │   └── schemas
        │       └── com.rafaelmardojai.SharePreview.gschema.xml
        ├── icons
        │   └── hicolor
        │       ├── scalable
        │       │   └── apps
        │       │       └── com.rafaelmardojai.SharePreview.svg
        │       └── symbolic
        │           └── apps
        │               └── com.rafaelmardojai.SharePreview-symbolic.svg
        ├── locale
        │   ├── es
        │   │   └── LC_MESSAGES
        │   │       └── share-preview.mo
        │   ├── it
        │   │   └── LC_MESSAGES
        │   │       └── share-preview.mo
        │   ├── nl
        │   │   └── LC_MESSAGES
        │   │       └── share-preview.mo
        │   └── tr
        │       └── LC_MESSAGES
        │           └── share-preview.mo
        ├── metainfo
        │   └── com.rafaelmardojai.SharePreview.metainfo.xml
        └── share-preview
            └── resources.gresource

```

In case you provide a binary (which is located at `usr/bin/share-preview` in my build) for future versions, I can easily modify the AUR build script to use it instead of my manually made package (and it would help other packagers too).

**Comment by rafaelmardojai** [comment]
Right, but what approach are you using to compile the binary?

**Comment by apandada1** [comment]
I was using Arch's automatic build system (`makepkg`). I figured this out after some trial and error. To manually build the binary, one needs to run the following commands.
```
meson builddir --prefix=/usr/
meson compile -C builddir
DESTDIR=output-directory meson install -C builddir
```
Then it would output the installation directory structure to `output-directory` inside `builddir` (you **don't** need to manually create it), which can be used in any distro (where libadwaita and gtk4 are already installed). Sometimes the second commands fails, and one needs to run it again (and rust would start again from where it failed).

**Comment by rafaelmardojai** [comment]
Right, so you would want a `.tar.gz` from the output-directory like the one you created or just the binary?

**Comment by apandada1** [comment]
I would prefer the .tar.gz from the output directory.

**Comment by rafaelmardojai** [comment]
Nice, I will do that for future releases!

**Comment by rafaelmardojai** [comment]
For some reason it compiles to 9mb for me.

**Comment by apandada1** [comment]
I have no idea why (it may be distro dependent). But 9mb is not too big either.
Is the directory structure the same?

**Comment by rafaelmardojai** [comment]
>  Is the directory structure the same?

Yeah, is the same.

**Pull request merged**
